root: true
env:
  node: true
  es2022: true
ignorePatterns:
  - '**/coverage/'
  - '**/dist/'
  - '**/generated/graphql.ts'
  - '**/node_modules/'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  project: './tsconfig.eslint.json' #['./packages/*/tsconfig.json']
  sourceType: module
  warnOnUnsupportedTypeScriptVersion: false,
plugins:
  - '@typescript-eslint'
  - unicorn
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:unicorn/recommended
overrides: [{ files: ['*.js'], extends: ['plugin:@typescript-eslint/disable-type-checked'] }]
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
      moduleDirectory: ['node_modules', 'src/']
rules:
  no-console: ['error']
  '@typescript-eslint/consistent-type-imports':
    - error
    - prefer: type-imports
      disallowTypeAnnotations: false
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  import/newline-after-import: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  unicorn/consistent-function-scoping:
    - error
    - checkArrowFunctions: false
  unicorn/no-array-for-each: off
  unicorn/no-array-reduce: off
  unicorn/no-null: off
  unicorn/no-useless-switch-case: off
  unicorn/prefer-dom-node-text-content: off
  unicorn/prefer-module: off
  unicorn/prefer-node-protocol: off
  unicorn/prefer-object-from-entries: off
  unicorn/prevent-abbreviations:
    - off
    - checkFilenames: false
      allowList:
        req: true
        res: true
        process-env: true
        ProcessEnv: true
