#!/bin/bash
# PostgeSQL init script
set -e

PG_SCHEMA=iex
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE SCHEMA IF NOT EXISTS $PG_SCHEMA AUTHORIZATION $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON SCHEMA public TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON SCHEMA $PG_SCHEMA TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $PG_SCHEMA TO $POSTGRES_USER;
EOSQL
