/** @type {import('./index.js').Schema} */
export const IexMarkdownSchema = {
  strip: ['script'],
  clobber: [],
  ancestors: {
    tbody: ['table'],
    tfoot: ['table'],
    thead: ['table'],
    td: ['table'],
    th: ['table'],
    tr: ['table']
  },
  protocols: {
    href: ['http', 'https', 'irc', 'ircs', 'mailto', 'xmpp'],
    cite: ['http', 'https'],
    src: ['http', 'https'],
    longDesc: ['http', 'https']
  },
  tagNames: [
    'a',
    'abbr',
    'audio',
    'b',
    'badge',
    'bdo',
    'blockquote',
    'box',
    'br',
    'caption',
    'cite',
    'code',
    'collapse',
    'containerdirective',
    'dd',
    'del',
    'details',
    'dfn',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'i',
    'img',
    'input',
    'ins',
    'insight',
    'insights',
    'katex',
    'kbd',
    'leafdirective',
    'li',
    'mark',
    'ol',
    'p',
    'path',
    'pre',
    'q',
    'rp',
    'rt',
    'ruby',
    's',
    'samp',
    'section',
    'small',
    'source',
    'span',
    'src',
    'strike',
    'strong',
    'sub',
    'summary',
    'sup',
    'svg',
    'table',
    'tbody',
    'td',
    'textdirective',
    'tfoot',
    'th',
    'thead',
    'time',
    'tr',
    'tt',
    'ul',
    'var',
    'vegachart',
    'video',
    'wbr',
    'xkcdchart'
  ],
  attributes: {
    a: ['href'],
    audio: ['controls', 'src'],
    blockquote: ['cite'],
    code: ['collapse', 'inline', 'lines', 'uri'],
    del: ['cite'],
    details: ['open'],
    div: ['display', 'height', 'itemScope', 'itemType', 'justifyContent', 'maxWidth', 'style', 'width'],
    img: [
      'alt',
      'borderRadius',
      'className',
      'display',
      'height',
      'longDesc',
      'objectFit',
      'objectPosition',
      'src',
      'width'
    ],
    input: [
      ['type', 'checkbox'],
      ['disabled', true]
    ],
    ins: ['cite'],
    insight: ['fullName', 'layout', 'showUpdatedAt'],
    insights: ['layout', 'query', 'showScores', 'showUpdatedAt', 'sortDirection', 'sortField'],
    katex: ['block', 'math'],
    li: [['className', 'task-list-item'], 'checked', 'ordered'],
    q: ['cite'],
    span: ['background'],
    vegachart: ['config'],
    video: ['autoplay', 'controls', 'loop', 'playsInline', 'src'],
    xkcdchart: ['config', 'xkcdType'],
    '*': [
      'abbr',
      'accept',
      'acceptCharset',
      'accessKey',
      'action',
      'align',
      'alt',
      'ariaDescribedBy',
      'ariaHidden',
      'ariaLabel',
      'ariaLabelledBy',
      'axis',
      'background',
      'backgroundColor',
      'bg',
      'border',
      'borderBottomColor',
      'borderColor',
      'borderLeftColor',
      'borderRadius',
      'borderRightColor',
      'borderStyle',
      'borderTopColor',
      'borderWidth',
      'boxSizing',
      'caption',
      'cellPadding',
      'cellSpacing',
      'char',
      'charOff',
      'charSet',
      'checked',
      'class',
      'className',
      'clear',
      'colSpan',
      'color',
      'colorScheme',
      'cols',
      'compact',
      'content',
      'coords',
      'cursor',
      'dateTime',
      'dir',
      'disabled',
      'display',
      'encType',
      'fontSize',
      'frame',
      'h',
      'hSpace',
      'headers',
      'height',
      'href',
      'hrefLang',
      'htmlFor',
      'id',
      'isMap',
      'itemProp',
      'itemScope',
      'itemType',
      'justifyContent',
      'label',
      'lang',
      'left',
      'margin',
      'marginBottom',
      'maxLength',
      'maxWidth',
      'media',
      'method',
      'mimeType',
      'multiple',
      'name',
      'noHref',
      'noShade',
      'noWrap',
      'open',
      'position',
      'prompt',
      'readOnly',
      'rel',
      'rev',
      'rowSpan',
      'rows',
      'rules',
      'scope',
      'selected',
      'shape',
      'size',
      'span',
      'start',
      'style',
      'summary',
      'tabIndex',
      'target',
      'title',
      'top',
      'type',
      'url',
      'useMap',
      'vAlign',
      'vSpace',
      'value',
      'variant',
      'w',
      'width',
      'z-index'
    ]
  },
  required: {
    input: {
      type: 'checkbox',
      disabled: true
    }
  }
};
