parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  warnOnUnsupportedTypeScriptVersion: false
plugins:
  - jsx-a11y
extends:
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
rules:
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-non-null-assertion': error
  no-console: ['off']
  unicorn/consistent-destructuring: off
  unicorn/consistent-function-scoping: off
  unicorn/filename-case: off
  unicorn/no-array-callback-reference: off
  unicorn/no-lonely-if: off
  unicorn/no-useless-undefined: off
  unicorn/prefer-export-from:
    - warn
    -
      ignoreUsedVariables: true
  unicorn/prefer-spread: off
  unicorn/prefer-ternary:
    - warn
    - only-single-line
