name: Lint
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Run ESLint
        run: npm ci && npm run bootstrap && npm run build:backend && npm run generate && npm run lint
      - uses: wagoid/commitlint-github-action@v4

