name: Test - Docker Action
on:
  push:
    branches:
      - 'feature/**'
  pull_request_review:
    types: [submitted]
    branches:
      - 'feature/**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            expediagroup/insights-explorer
          tags: |
            type=ref,event=pr

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


